use crate::{CompatibilityMethod, ToolKind, ToolSpec};

const fn read(
    name: &'static str,
    title: &'static str,
    category: &'static str,
    endpoint: &'static str,
) -> ToolSpec {
    ToolSpec {
        name,
        title,
        category,
        description: "Read the requested UniFi Network compatibility resource; controller support is capability-dependent.",
        kind: ToolKind::Compatibility {
            endpoint,
            method: CompatibilityMethod::Get,
            id_arg: None,
            read_only: true,
            destructive: false,
            idempotent: true,
        },
    }
}
#[allow(clippy::too_many_arguments)]
const fn write(
    name: &'static str,
    title: &'static str,
    category: &'static str,
    endpoint: &'static str,
    method: CompatibilityMethod,
    id_arg: Option<&'static str>,
    destructive: bool,
    idempotent: bool,
) -> ToolSpec {
    ToolSpec {
        name,
        title,
        category,
        description: "Preview and, after explicit confirmation, perform this UniFi Network compatibility operation.",
        kind: ToolKind::Compatibility {
            endpoint,
            method,
            id_arg,
            read_only: false,
            destructive,
            idempotent,
        },
    }
}

pub(crate) const COMPATIBILITY_TOOLS: &[ToolSpec] = &[
    read(
        "unifi_batch_status",
        "Batch Status",
        "system",
        "cmd/batch-status",
    ),
    write(
        "unifi_load_tools",
        "Load Tools",
        "system",
        "stat/sysinfo",
        CompatibilityMethod::Get,
        None,
        false,
        true,
    ),
    read(
        "unifi_subscribe_events",
        "Subscribe Events",
        "events",
        "stat/event",
    ),
    write(
        "unifi_archive_alarm",
        "Archive Alarm",
        "events",
        "cmd/alarm",
        CompatibilityMethod::Post,
        Some("alarm_id"),
        false,
        true,
    ),
    write(
        "unifi_archive_all_alarms",
        "Archive All Alarms",
        "events",
        "cmd/alarm",
        CompatibilityMethod::Post,
        None,
        false,
        true,
    ),
    write(
        "unifi_configure_port_aggregation",
        "Configure Port Aggregation",
        "switch",
        "rest/device",
        CompatibilityMethod::Post,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_configure_port_mirror",
        "Configure Port Mirror",
        "switch",
        "rest/device",
        CompatibilityMethod::Post,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_create_ap_group",
        "Create AP Group",
        "wireless",
        "rest/apgroup",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_backup",
        "Create Backup",
        "system",
        "cmd/backup",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_client_group",
        "Create Client Group",
        "clients",
        "rest/networkmember",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_dns_record",
        "Create DNS Record",
        "dns",
        "rest/staticdns",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_dynamic_dns",
        "Create Dynamic DNS",
        "dns",
        "rest/dynamicdns",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_firewall_group",
        "Create Firewall Group",
        "firewall",
        "rest/firewallgroup",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_oon_policy",
        "Create OON Policy",
        "security",
        "rest/oon",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_port_forward",
        "Create Port Forward",
        "routing",
        "rest/portforward",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_port_profile",
        "Create Port Profile",
        "switch",
        "rest/portconf",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_qos_rule",
        "Create QoS Rule",
        "qos",
        "rest/qosrule",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_route",
        "Create Route",
        "routing",
        "rest/routing",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_simple_port_forward",
        "Create Simple Port Forward",
        "routing",
        "rest/portforward",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_simple_qos_rule",
        "Create Simple QoS Rule",
        "qos",
        "rest/qosrule",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_usergroup",
        "Create User Group",
        "clients",
        "rest/usergroup",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_create_voucher",
        "Create Voucher",
        "hotspot",
        "cmd/hotspot",
        CompatibilityMethod::Post,
        None,
        false,
        false,
    ),
    write(
        "unifi_delete_ap_group",
        "Delete AP Group",
        "wireless",
        "rest/apgroup/{id}",
        CompatibilityMethod::Delete,
        Some("ap_group_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_backup",
        "Delete Backup",
        "system",
        "cmd/backup/{id}",
        CompatibilityMethod::Delete,
        Some("backup_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_client_group",
        "Delete Client Group",
        "clients",
        "rest/networkmember/{id}",
        CompatibilityMethod::Delete,
        Some("client_group_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_content_filter",
        "Delete Content Filter",
        "security",
        "rest/content-filtering/{id}",
        CompatibilityMethod::Delete,
        Some("content_filter_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_dns_record",
        "Delete DNS Record",
        "dns",
        "rest/staticdns/{id}",
        CompatibilityMethod::Delete,
        Some("dns_record_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_dynamic_dns",
        "Delete Dynamic DNS",
        "dns",
        "rest/dynamicdns/{id}",
        CompatibilityMethod::Delete,
        Some("entry_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_firewall_group",
        "Delete Firewall Group",
        "firewall",
        "rest/firewallgroup/{id}",
        CompatibilityMethod::Delete,
        Some("firewall_group_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_oon_policy",
        "Delete OON Policy",
        "security",
        "rest/oon/{id}",
        CompatibilityMethod::Delete,
        Some("policy_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_port_forward",
        "Delete Port Forward",
        "routing",
        "rest/portforward/{id}",
        CompatibilityMethod::Delete,
        Some("port_forward_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_port_profile",
        "Delete Port Profile",
        "switch",
        "rest/portconf/{id}",
        CompatibilityMethod::Delete,
        Some("port_profile_id"),
        true,
        true,
    ),
    write(
        "unifi_delete_vpn_client",
        "Delete VPN Client",
        "vpn",
        "rest/networkconf/{id}",
        CompatibilityMethod::Delete,
        Some("client_id"),
        true,
        true,
    ),
    write(
        "unifi_forget_client",
        "Forget Client",
        "clients",
        "cmd/stamgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        true,
        true,
    ),
    write(
        "unifi_locate_device",
        "Locate Device",
        "devices",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_rename_client",
        "Rename Client",
        "clients",
        "cmd/stamgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_rename_device",
        "Rename Device",
        "devices",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_set_client_ip_settings",
        "Set Client IP Settings",
        "clients",
        "cmd/stamgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_set_device_led",
        "Set Device LED",
        "devices",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_set_jumbo_frames",
        "Set Jumbo Frames",
        "switch",
        "rest/device",
        CompatibilityMethod::Post,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_set_outlet_state",
        "Set Outlet State",
        "switch",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("device_id"),
        true,
        true,
    ),
    write(
        "unifi_set_site_leds",
        "Set Site LEDs",
        "devices",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        None,
        false,
        true,
    ),
    write(
        "unifi_set_switch_port_profile",
        "Set Switch Port Profile",
        "switch",
        "rest/device",
        CompatibilityMethod::Post,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_device",
        "Toggle Device",
        "devices",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        true,
        true,
    ),
    write(
        "unifi_toggle_firewall_policy",
        "Toggle Firewall Policy",
        "firewall",
        "rest/firewallrule/{id}",
        CompatibilityMethod::Put,
        Some("firewall_policy_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_oon_policy",
        "Toggle OON Policy",
        "security",
        "rest/oon/{id}",
        CompatibilityMethod::Put,
        Some("policy_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_port_forward",
        "Toggle Port Forward",
        "routing",
        "rest/portforward/{id}",
        CompatibilityMethod::Put,
        Some("port_forward_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_qos_rule_enabled",
        "Toggle QoS Rule",
        "qos",
        "rest/qosrule/{id}",
        CompatibilityMethod::Put,
        Some("qos_rule_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_traffic_route",
        "Toggle Traffic Route",
        "routing",
        "rest/trafficroute/{id}",
        CompatibilityMethod::Put,
        Some("traffic_route_id"),
        false,
        true,
    ),
    write(
        "unifi_toggle_wlan",
        "Toggle WLAN",
        "wireless",
        "rest/wlanconf/{id}",
        CompatibilityMethod::Put,
        Some("wlan_id"),
        false,
        true,
    ),
    write(
        "unifi_trigger_rf_scan",
        "Trigger RF Scan",
        "wireless",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("mac_address"),
        false,
        true,
    ),
    write(
        "unifi_trigger_speedtest",
        "Trigger Speed Test",
        "statistics",
        "cmd/devmgr",
        CompatibilityMethod::Post,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_update_ap_group",
        "Update AP Group",
        "wireless",
        "rest/apgroup/{id}",
        CompatibilityMethod::Put,
        Some("ap_group_id"),
        false,
        true,
    ),
    write(
        "unifi_update_autobackup_settings",
        "Update Auto-backup Settings",
        "system",
        "rest/setting/auto-backup",
        CompatibilityMethod::Put,
        None,
        false,
        true,
    ),
    write(
        "unifi_update_client_group",
        "Update Client Group",
        "clients",
        "rest/networkmember/{id}",
        CompatibilityMethod::Put,
        Some("client_group_id"),
        false,
        true,
    ),
    write(
        "unifi_update_content_filter",
        "Update Content Filter",
        "security",
        "rest/content-filtering/{id}",
        CompatibilityMethod::Put,
        Some("content_filter_id"),
        false,
        true,
    ),
    write(
        "unifi_update_device_radio",
        "Update Device Radio",
        "wireless",
        "rest/device/{id}",
        CompatibilityMethod::Put,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_update_dns_record",
        "Update DNS Record",
        "dns",
        "rest/staticdns/{id}",
        CompatibilityMethod::Put,
        Some("dns_record_id"),
        false,
        true,
    ),
    write(
        "unifi_update_dynamic_dns",
        "Update Dynamic DNS",
        "dns",
        "rest/dynamicdns/{id}",
        CompatibilityMethod::Put,
        Some("entry_id"),
        false,
        true,
    ),
    write(
        "unifi_update_firewall_group",
        "Update Firewall Group",
        "firewall",
        "rest/firewallgroup/{id}",
        CompatibilityMethod::Put,
        Some("firewall_group_id"),
        false,
        true,
    ),
    write(
        "unifi_update_gateway_settings",
        "Update Gateway Settings",
        "system",
        "rest/setting",
        CompatibilityMethod::Put,
        None,
        false,
        true,
    ),
    write(
        "unifi_update_oon_policy",
        "Update OON Policy",
        "security",
        "rest/oon/{id}",
        CompatibilityMethod::Put,
        Some("policy_id"),
        false,
        true,
    ),
    write(
        "unifi_update_port_forward",
        "Update Port Forward",
        "routing",
        "rest/portforward/{id}",
        CompatibilityMethod::Put,
        Some("port_forward_id"),
        false,
        true,
    ),
    write(
        "unifi_update_port_profile",
        "Update Port Profile",
        "switch",
        "rest/portconf/{id}",
        CompatibilityMethod::Put,
        Some("port_profile_id"),
        false,
        true,
    ),
    write(
        "unifi_update_qos_rule",
        "Update QoS Rule",
        "qos",
        "rest/qosrule/{id}",
        CompatibilityMethod::Put,
        Some("qos_rule_id"),
        false,
        true,
    ),
    write(
        "unifi_update_route",
        "Update Route",
        "routing",
        "rest/routing/{id}",
        CompatibilityMethod::Put,
        Some("route_id"),
        false,
        true,
    ),
    write(
        "unifi_update_snmp_settings",
        "Update SNMP Settings",
        "system",
        "rest/setting/snmp",
        CompatibilityMethod::Put,
        None,
        false,
        true,
    ),
    write(
        "unifi_update_switch_stp",
        "Update Switch STP",
        "switch",
        "rest/device/{id}",
        CompatibilityMethod::Put,
        Some("device_id"),
        false,
        true,
    ),
    write(
        "unifi_update_traffic_route",
        "Update Traffic Route",
        "routing",
        "rest/trafficroute/{id}",
        CompatibilityMethod::Put,
        Some("traffic_route_id"),
        false,
        true,
    ),
    write(
        "unifi_update_usergroup",
        "Update User Group",
        "clients",
        "rest/usergroup/{id}",
        CompatibilityMethod::Put,
        Some("usergroup_id"),
        false,
        true,
    ),
    write(
        "unifi_update_vpn_client_state",
        "Update VPN Client State",
        "vpn",
        "rest/networkconf/{id}",
        CompatibilityMethod::Put,
        Some("client_id"),
        false,
        true,
    ),
    write(
        "unifi_update_vpn_server_state",
        "Update VPN Server State",
        "vpn",
        "rest/networkconf/{id}",
        CompatibilityMethod::Put,
        Some("server_id"),
        false,
        true,
    ),
];
